version: '3'
services:
  web:
    image: node:18.x # Imagem base do Docker para o Node.js
    build: ./dist
    working_dir: /app # Diretório de trabalho dentro do contêiner
    volumes:
      - ./dist:/app # Mapeamento do diretório do host para o diretório de trabalho do contêiner
    ports:
      - "3000:3000" # Porta do host:porta do contêiner
    environment:
      - NODE_ENV=production # Defina a variável de ambiente NODE_ENV para 'production'
    command: node index.js # Comando para iniciar o aplicativo Node.js